version: 2.1

#
# Variables
#

project_directory: &project_directory ~/project

#
# Jobs
#

jobs:
  test:
    working_directory: *project_directory
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: "15.2"
    steps:
      - checkout
      - run:
          name: Test
          command: |
            set -o pipefail && xcodebuild -project LoopKit.xcodeproj -scheme Shared build -destination 'name=iPhone 15 Pro' test | xcpretty
      - run:
          name: Build Swift Package
          command: |
            swift build -v -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios17.0-simulator" | xcpretty
      - store_test_results:
          path: test_output
#
# Workflows
#

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
